Fixed workflow

diff --git a/.github/workflows/pr_checks.yml b/.github/workflows/pr_checks.yml
--- a/.github/workflows/pr_checks.yml
+++ b/.github/workflows/pr_checks.yml
@@ -85,11 +85,17 @@ jobs:
 
       - name: Run Dependency Guard
         id: dependency-guard
-        run: ./gradlew modo-compose:dependencyGuard
+        run: |
+          if ./gradlew modo-compose:dependencyGuard; then
+            echo "result=success" >> $GITHUB_OUTPUT
+          else
+            echo "result=failure" >> $GITHUB_OUTPUT
+            exit 1
+          fi
         continue-on-error: true
 
       - name: Comment on PR if Dependency Guard fails
-        if: failure() && steps.dependency-guard.conclusion == 'failure'
+        if: steps.dependency-guard.outputs.result == 'failure'
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           header: dependency-guard
@@ -116,12 +122,12 @@ jobs:
             Please address these issues before merging this PR.
 
       - name: Remove dependency guard comment if check passes
-        if: steps.dependency-guard.conclusion == 'success'
+        if: steps.dependency-guard.outputs.result == 'success'
         uses: marocchino/sticky-pull-request-comment@v2
         with:
           header: dependency-guard
           delete: true
 
       - name: Fail job if Dependency Guard failed
-        if: steps.dependency-guard.conclusion == 'failure'
+        if: steps.dependency-guard.outputs.result == 'failure'
         run: exit 1
